name: DockerHub Publish
on:
  push:
    branches:
      - master
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    name: A job to build and push to DockerHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Tags
        run: echo "tags=$(echo $GITHUB_REPOSITORY | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          # cache-from: type=registry,ref=$(cat REPOSITORY)
          cache-from: type=registry,ref=${{ env.tags }}
          cache-to: type=inline
          # tags: "$(cat REPOSITORY)"
          tags: ${{ env.tags }}
          build-args: WWWGROUP=1000
